import { PackageFile } from '../types';

export const PACKAGE_FILES: PackageFile[] = [
  {
    path: 'DESCRIPTION',
    name: 'DESCRIPTION',
    category: 'core',
    language: 'dcf',
    description: 'R Package manifest containing metadata, dependencies, authors, and system requirements.',
    content: `Package: rs.ui.windows
Type: Package
Title: Custom UI Theming and Orange Pixel Cat for RStudio Desktop on Windows
Version: 0.1.1
Authors@R: person("rs.ui", "Contributors", email = "rs.ui.windows@example.com", role = c("aut", "cre"))
Description: A Windows port and extension of the 'rs.ui' concept for RStudio Desktop.
    Allows users to customize the full RStudio Desktop Windows UI theme with custom accent
    colors, derivative palettes, and an embedded persistent orange pixel cat widget.
    Includes automated discovery of RStudio installations on Windows, safe SHA256-verified
    backups, non-destructive patching, rollback restore routines, dry-run verification, and
    detailed status diagnostic reporting.
License: MIT + file LICENSE
URL: https://github.com/TheMostAncientDream-1864/orange-cat-theme
BugReports: https://github.com/TheMostAncientDream-1864/orange-cat-theme/issues
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.2.3
Depends:
    R (>= 3.6.0)
Imports:
    jsonlite,
    tools,
    utils
Suggests:
    testthat (>= 3.0.0)
Config/testthat/edition: 3
SystemRequirements: Windows 10 or Windows 11 (64-bit), RStudio Desktop`,
  },
  {
    path: 'NAMESPACE',
    name: 'NAMESPACE',
    category: 'core',
    language: 'r',
    description: 'Export declarations and package namespace bindings.',
    content: `# Generated by roxygen2: do not edit by hand

export(rs.ui)
export(rs.ui.backup)
export(rs.ui.detect)
export(rs.ui.restore)
export(rs.ui.status)

importFrom(jsonlite, fromJSON)
importFrom(jsonlite, toJSON)
importFrom(tools, md5sum)
importFrom(utils, read.table)`,
  },
  {
    path: 'README.md',
    name: 'README.md',
    category: 'docs',
    language: 'markdown',
    description: 'Complete documentation, usage guides, administrator elevation instructions, and architecture comparison.',
    content: `# rs.ui.windows 🐱🟧

> **Windows Port & Modern Customizer for RStudio Desktop UI with Orange Pixel Cat Integration**

## Overview
Standard .rstheme files in RStudio only style the Ace editor. rs.ui.windows customizes the full RStudio Desktop Windows outer interface (menubars, tabs, window frames, toolbars) and places an authentic Orange Pixel Cat directly in the header bar.

## Installation
\`\`\`r
# Install rs.ui.windows directly from GitHub root
remotes::install_github("TheMostAncientDream-1864/orange-cat-theme")
\`\`\`

## Usage
\`\`\`r
library(rs.ui.windows)

# Apply orange UI theme + Orange Pixel Cat
rs.ui(main_color = "#dc6601")

# Test without modifying files
rs.ui(main_color = "#dc6601", dry_run = TRUE)

# Inspect diagnostics
rs.ui.status()

# 1-Click Restore to original
rs.ui.restore()
\`\`\``,
  },
  {
    path: 'R/rs_ui.R',
    name: 'rs_ui.R',
    category: 'r',
    language: 'r',
    description: 'Main user-facing API functions: rs.ui(), rs.ui.status(), rs.ui.backup().',
    content: `#' Customize RStudio Desktop UI on Windows
#'
#' @param main_color Hex string of main accent color (default: "#dc6601").
#' @param cat_svg_path Optional custom path to SVG file for the pixel cat icon.
#' @param custom_path Optional path to RStudio Desktop installation directory.
#' @param dry_run Logical. If TRUE, runs all detection/validation without file edits.
#' @export
rs.ui <- function(main_color = "#dc6601",
                  cat_svg_path = NULL,
                  custom_path = NULL,
                  dry_run = FALSE) {
  apply_ui_patch(
    main_color = main_color,
    cat_svg_path = cat_svg_path,
    custom_path = custom_path,
    dry_run = dry_run
  )
}

#' Diagnostic Status of RStudio UI Customization
#' @export
rs.ui.status <- function(custom_path = NULL) {
  detected <- rs.ui.detect(custom_path = custom_path)
  storage_dir <- get_user_storage_dir()
  meta <- get_latest_backup_metadata(storage_dir)

  is_customized <- FALSE
  if (isTRUE(detected$detected) && file.exists(detected$index_htm)) {
    idx_content <- paste(readLines(detected$index_htm, warn = FALSE, encoding = "UTF-8"), collapse = "\\n")
    is_customized <- grepl("rs-ui-custom-theme", idx_content, fixed = TRUE)
  }

  cat("\\n============================================================\\n")
  cat("         rs.ui.windows - RStudio Desktop Status\\n")
  cat("============================================================\\n")
  cat("OS Platform            : ", .Platform$OS.type, " (", Sys.info()[["sysname"]], ")\\n", sep = "")
  cat("RStudio detected       : ", if (isTRUE(detected$detected)) "TRUE" else "FALSE", "\\n", sep = "")
  cat("RStudio version        : ", detected$version, "\\n", sep = "")
  cat("RStudio architecture   : ", detected$architecture, "\\n", sep = "")
  cat("RStudio running        : ", if (isTRUE(detected$is_running)) "YES (active)" else "NO", "\\n", sep = "")
  cat("Installation path      : ", detected$rstudio_dir, "\\n", sep = "")
  cat("Write permissions      : ", if (isTRUE(detected$is_writable)) "OK (Writable)" else "RESTRICTED (Admin needed)", "\\n", sep = "")
  cat("Customization state    : ", if (is_customized) "ACTIVE (Patched with Orange Cat)" else "DEFAULT (Un-modded)", "\\n", sep = "")
  cat("Backup available       : ", if (!is.null(meta)) paste0("YES (", meta$rstudio_version, ")") else "NONE", "\\n", sep = "")
  cat("============================================================\\n\\n")

  invisible(list(
    detected = detected$detected,
    version = detected$version,
    customized = is_customized,
    backup_meta = meta
  ))
}

#' Explicitly Create a UI Backup Without Patching
#' @export
rs.ui.backup <- function(custom_path = NULL, force = FALSE) {
  detected <- rs.ui.detect(custom_path = custom_path)
  create_ui_backup(detected, force = force)
}`,
  },
  {
    path: 'R/detect_rstudio.R',
    name: 'detect_rstudio.R',
    category: 'r',
    language: 'r',
    description: 'Windows RStudio installation discovery across Program Files, LocalAppData, Registry, and custom paths.',
    content: `#' Detect RStudio Desktop Installation on Windows
#' @export
rs.ui.detect <- function(custom_path = NULL) {
  candidates <- character(0)

  if (!is.null(custom_path) && nzchar(custom_path)) {
    candidates <- c(candidates, normalizePath(custom_path, winslash = "/", mustWork = FALSE))
  }

  env_desktop <- Sys.getenv("RSTUDIO_DESKTOP_DIR", "")
  if (nzchar(env_desktop)) candidates <- c(candidates, env_desktop)

  if (.Platform$OS.type == "windows") {
    reg_keys <- c("Software\\\\RStudio", "Software\\\\Posit\\\\RStudio", "Software\\\\WOW6432Node\\\\RStudio")
    for (key in reg_keys) {
      tryCatch({
        val <- utils::readRegistry(key, hive = "HLM", maxdepth = 2)
        if (!is.null(val$InstallPath)) candidates <- c(candidates, val$InstallPath)
      }, error = function(e) NULL)
    }
  }

  prog_files <- Sys.getenv("ProgramFiles", "C:/Program Files")
  prog_files_x86 <- Sys.getenv("ProgramFiles(x86)", "C:/Program Files (x86)")
  local_app_data <- Sys.getenv("LOCALAPPDATA", "")

  candidates <- c(
    candidates,
    file.path(prog_files, "RStudio"),
    file.path(prog_files, "Posit", "RStudio"),
    file.path(prog_files_x86, "RStudio"),
    if (nzchar(local_app_data)) file.path(local_app_data, "Programs", "RStudio") else character(0),
    "C:/RStudio"
  )

  candidates <- unique(candidates[nzchar(candidates)])
  detected_info <- NULL

  for (cand in candidates) {
    norm_cand <- tryCatch(normalizePath(cand, winslash = "/", mustWork = FALSE), error = function(e) cand)
    if (!dir.exists(norm_cand)) next

    # 1. Primary Electron layout (2022.07 - 2026+)
    electron_index_1 <- file.path(norm_cand, "resources", "app", "www", "index.htm")
    if (file.exists(electron_index_1)) {
      detected_info <- list(
        detected = TRUE,
        rstudio_dir = normalizePath(norm_cand, winslash = "/", mustWork = FALSE),
        index_htm = normalizePath(electron_index_1, winslash = "/", mustWork = FALSE),
        www_dir = normalizePath(file.path(norm_cand, "resources", "app", "www"), winslash = "/", mustWork = FALSE),
        architecture = "electron"
      )
      break
    }

    # 2. Nested Electron layout
    electron_index_2 <- file.path(norm_cand, "resources", "app", "resources", "www", "index.htm")
    if (file.exists(electron_index_2)) {
      detected_info <- list(
        detected = TRUE,
        rstudio_dir = normalizePath(norm_cand, winslash = "/", mustWork = FALSE),
        index_htm = normalizePath(electron_index_2, winslash = "/", mustWork = FALSE),
        www_dir = normalizePath(file.path(norm_cand, "resources", "app", "resources", "www"), winslash = "/", mustWork = FALSE),
        architecture = "electron"
      )
      break
    }

    # 3. Root resources layout
    electron_index_3 <- file.path(norm_cand, "resources", "www", "index.htm")
    if (file.exists(electron_index_3)) {
      detected_info <- list(
        detected = TRUE,
        rstudio_dir = normalizePath(norm_cand, winslash = "/", mustWork = FALSE),
        index_htm = normalizePath(electron_index_3, winslash = "/", mustWork = FALSE),
        www_dir = normalizePath(file.path(norm_cand, "resources", "www"), winslash = "/", mustWork = FALSE),
        architecture = "electron"
      )
      break
    }

    # 4. Legacy Qt layout (< 2022.07)
    qt_index <- file.path(norm_cand, "www", "index.htm")
    if (file.exists(qt_index)) {
      detected_info <- list(
        detected = TRUE,
        rstudio_dir = normalizePath(norm_cand, winslash = "/", mustWork = FALSE),
        index_htm = normalizePath(qt_index, winslash = "/", mustWork = FALSE),
        www_dir = normalizePath(file.path(norm_cand, "www"), winslash = "/", mustWork = FALSE),
        architecture = "qt"
      )
      break
    }
  }

  if (is.null(detected_info)) {
    return(list(detected = FALSE, status_message = "RStudio Desktop not detected."))
  }

  detected_info$version <- detect_rstudio_version(detected_info$rstudio_dir)
  detected_info$is_running <- is_rstudio_running()
  detected_info$is_writable <- is_path_writable(detected_info$index_htm)
  detected_info
}`,
  },
  {
    path: 'R/backup.R',
    name: 'backup.R',
    category: 'r',
    language: 'r',
    description: 'Safe SHA256/MD5 verified backup creation, un-modded base preservation, and metadata recording.',
    content: `#' Create a safe backup of RStudio UI files
create_ui_backup <- function(detected_info, force = FALSE) {
  storage_dir <- get_user_storage_dir()
  ver_tag <- gsub("[^a-zA-Z0-9._-]", "_", detected_info$version)
  backup_dir <- file.path(storage_dir, "backups", paste0("RStudio-version-", ver_tag))
  meta_file <- file.path(backup_dir, "metadata.json")

  if (dir.exists(backup_dir) && file.exists(meta_file) && !force) {
    return(list(success = TRUE, backup_dir = backup_dir, is_new = FALSE))
  }

  dir.create(backup_dir, recursive = TRUE, showWarnings = FALSE)
  dest_index <- file.path(backup_dir, "index.htm")
  file.copy(detected_info$index_htm, dest_index, overwrite = TRUE)

  orig_hash <- calculate_file_hash(detected_info$index_htm)
  backup_hash <- calculate_file_hash(dest_index)

  if (!identical(orig_hash, backup_hash)) {
    stop("Backup verification failed: Hash mismatch!", call. = FALSE)
  }

  metadata <- list(
    package = "rs.ui.windows",
    created_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
    rstudio_version = detected_info$version,
    architecture = detected_info$architecture,
    files = list(
      index_htm = list(
        original_path = detected_info$index_htm,
        backup_path = dest_index,
        original_hash = orig_hash,
        backup_hash = backup_hash
      )
    )
  )

  jsonlite::write_json(metadata, meta_file, pretty = TRUE, auto_unbox = TRUE)
  list(success = TRUE, backup_dir = backup_dir, metadata = metadata, is_new = TRUE)
}`,
  },
  {
    path: 'R/patch.R',
    name: 'patch.R',
    category: 'r',
    language: 'r',
    description: 'Atomic verified patching workflow (detect -> validate -> backup -> patch -> verify).',
    content: `#' Safe Patching Routine
apply_ui_patch <- function(main_color = "#dc6601",
                           cat_svg_path = NULL,
                           custom_path = NULL,
                           dry_run = FALSE) {
  # 1. Detect
  detected <- rs.ui.detect(custom_path = custom_path)
  if (!isTRUE(detected$detected)) stop("RStudio Desktop not detected.", call. = FALSE)

  if (isTRUE(dry_run)) {
    cat("Dry run completed: all prerequisites verified.\n")
    return(invisible(list(success = TRUE, dry_run = TRUE)))
  }

  # 2. Backup
  backup_res <- create_ui_backup(detected)

  # 3. Generate CSS
  target_css <- file.path(detected$www_dir, "rs.ui.css")
  generate_theme_css(main_color = main_color, cat_svg_path = cat_svg_path, output_file = target_css)

  # 4. Patch index.htm
  index_content <- paste(readLines(detected$index_htm, warn = FALSE, encoding = "UTF-8"), collapse = "\\n")
  link_tag <- '<link rel="stylesheet" id="rs-ui-custom-theme" href="rs.ui.css" type="text/css" />'

  if (!grepl("rs-ui-custom-theme", index_content, fixed = TRUE)) {
    new_index <- sub("(?i)</head>", paste0("  ", link_tag, "\\n</head>"), index_content, perl = TRUE)
    writeLines(new_index, detected$index_htm, useBytes = TRUE)
  }

  # 5. Verify
  patched <- paste(readLines(detected$index_htm, warn = FALSE, encoding = "UTF-8"), collapse = "\\n")
  if (!grepl("rs-ui-custom-theme", patched, fixed = TRUE)) {
    rs.ui.restore(custom_path = detected$rstudio_dir)
    stop("Patch verification failed; rolled back to original.", call. = FALSE)
  }
  cat("==> Patch applied and verified successfully!\n")
}`,
  },
  {
    path: 'R/restore.R',
    name: 'restore.R',
    category: 'r',
    language: 'r',
    description: 'Pristine rollback engine restoring original index.htm and removing custom CSS.',
    content: `#' Restore Original RStudio Desktop UI Files
#' @export
rs.ui.restore <- function(custom_path = NULL, force = FALSE) {
  detected <- rs.ui.detect(custom_path = custom_path)
  storage_dir <- get_user_storage_dir()
  meta <- get_latest_backup_metadata(storage_dir)

  if (is.null(meta)) stop("No backup metadata found in storage.", call. = FALSE)

  backup_index <- meta$files$index_htm$backup_path
  file.copy(backup_index, detected$index_htm, overwrite = TRUE)

  target_css <- file.path(detected$www_dir, "rs.ui.css")
  if (file.exists(target_css)) unlink(target_css)

  cat("==> Original RStudio UI successfully restored from verified backup!\n")
  invisible(TRUE)
}`,
  },
  {
    path: 'R/css_generator.R',
    name: 'css_generator.R',
    category: 'r',
    language: 'r',
    description: 'Dynamic CSS generation, palette calculation, and Base64 SVG Cat embedding.',
    content: `#' Generate Custom CSS with Orange Pixel Cat
generate_theme_css <- function(main_color = "#dc6601",
                               cat_svg_path = NULL,
                               output_file = NULL) {
  palette <- derive_theme_palette(main_color)
  cat_data_uri <- svg_to_data_uri(system.file("assets", "cat.svg", package = "rs.ui.windows"))

  base_css_file <- system.file("css", "base.css", package = "rs.ui.windows")
  css_template <- paste(readLines(base_css_file, warn = FALSE, encoding = "UTF-8"), collapse = "\\n")

  compiled <- css_template
  compiled <- gsub("\\\\{\\\\{MAIN_COLOR\\\\}\\\\}", palette$main_color, compiled)
  compiled <- gsub("\\\\{\\\\{LIGHT_COLOR\\\\}\\\\}", palette$light_color, compiled)
  compiled <- gsub("\\\\{\\\\{DARK_COLOR\\\\}\\\\}", palette$dark_color, compiled)
  compiled <- gsub("\\\\{\\\\{BG_TINT\\\\}\\\\}", palette$bg_tint, compiled)
  compiled <- gsub("\\\\{\\\\{BORDER_COLOR\\\\}\\\\}", palette$border_color, compiled)
  compiled <- gsub("\\\\{\\\\{HOVER_COLOR\\\\}\\\\}", palette$hover_color, compiled)
  compiled <- gsub("\\\\{\\\\{ACTIVE_COLOR\\\\}\\\\}", palette$active_color, compiled)
  compiled <- gsub("\\\\{\\\\{CAT_SVG_DATA_URI\\\\}\\\\}", cat_data_uri, compiled)

  if (!is.null(output_file)) {
    writeLines(compiled, output_file, useBytes = TRUE)
  }
  invisible(compiled)
}`,
  },
  {
    path: 'R/version_check.R',
    name: 'version_check.R',
    category: 'r',
    language: 'r',
    description: 'Version inspection from package.json, VERSION file, and version drift comparison.',
    content: `#' Detect RStudio Version
detect_rstudio_version <- function(rstudio_dir) {
  pkg_json <- file.path(rstudio_dir, "resources", "app", "package.json")
  if (file.exists(pkg_json)) {
    pkg <- tryCatch(jsonlite::fromJSON(pkg_json), error = function(e) NULL)
    if (!is.null(pkg$version)) return(as.character(pkg$version))
  }
  ver_file <- file.path(rstudio_dir, "VERSION")
  if (file.exists(ver_file)) {
    lines <- readLines(ver_file, warn = FALSE)
    if (length(lines) > 0) return(trimws(lines[1]))
  }
  "unknown"
}`,
  },
  {
    path: 'R/utils.R',
    name: 'utils.R',
    category: 'r',
    language: 'r',
    description: 'RGB/Hex math, Windows LocalAppData discovery, Base64 encoder, process status.',
    content: `#' Utility functions for rs.ui.windows
hex_to_rgb <- function(hex) {
  clean <- gsub("^#", "", trimws(hex))
  r <- strtoi(substr(clean, 1, 2), base = 16)
  g <- strtoi(substr(clean, 3, 4), base = 16)
  b <- strtoi(substr(clean, 5, 6), base = 16)
  c(r = r, g = g, b = b)
}

rgb_to_hex <- function(rgb) {
  sprintf("#%02x%02x%02x", rgb[1], rgb[2], rgb[3])
}

lighten_hex <- function(hex, factor = 0.25) {
  rgb <- hex_to_rgb(hex)
  rgb_to_hex(rgb + (255 - rgb) * factor)
}

darken_hex <- function(hex, factor = 0.25) {
  rgb <- hex_to_rgb(hex)
  rgb_to_hex(rgb * (1 - factor))
}

svg_to_data_uri <- function(svg_content) {
  raw_bytes <- charToRaw(svg_content)
  paste0("data:image/svg+xml;base64,", jsonlite::base64_enc(raw_bytes))
}`,
  },
  {
    path: 'inst/assets/cat.svg',
    name: 'cat.svg',
    category: 'inst',
    language: 'xml',
    description: 'Authentic 24x18 pixel art SVG of the orange cat mascot with sparkling eyes and whiskers.',
    content: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 18" width="48" height="36" shape-rendering="crispEdges">
  <defs>
    <style>
      .o { fill: #1e130a; }
      .f { fill: #dc6601; }
      .l { fill: #ff8e32; }
      .s { fill: #b84f00; }
      .w { fill: #fff5eb; }
      .p { fill: #ff7597; }
      .e { fill: #0f0a06; }
      .h { fill: #ffffff; }
    </style>
  </defs>
  <!-- Ear tips -->
  <rect x="3" y="1" width="3" height="1" class="o"/>
  <rect x="18" y="1" width="3" height="1" class="o"/>
  <!-- Row 1 -->
  <rect x="2" y="2" width="1" height="3" class="o"/>
  <rect x="3" y="2" width="3" height="1" class="f"/>
  <rect x="6" y="2" width="1" height="1" class="o"/>
  <rect x="17" y="2" width="1" height="1" class="o"/>
  <rect x="18" y="2" width="3" height="1" class="f"/>
  <rect x="21" y="2" width="1" height="3" class="o"/>
  <!-- Row 2: Inner Ears & Top Head -->
  <rect x="3" y="3" width="1" height="2" class="f"/>
  <rect x="4" y="3" width="2" height="2" class="p"/>
  <rect x="6" y="3" width="1" height="1" class="o"/>
  <rect x="7" y="3" width="10" height="1" class="o"/>
  <rect x="17" y="3" width="1" height="1" class="o"/>
  <rect x="18" y="3" width="2" height="2" class="p"/>
  <rect x="20" y="3" width="1" height="2" class="f"/>
  <!-- Row 3: Head top fur -->
  <rect x="7" y="4" width="10" height="1" class="l"/>
  <!-- Row 4: Forehead -->
  <rect x="1" y="5" width="1" height="7" class="o"/>
  <rect x="2" y="5" width="20" height="2" class="f"/>
  <rect x="22" y="5" width="1" height="7" class="o"/>
  <rect x="11" y="4" width="2" height="3" class="s"/>
  <rect x="7" y="5" width="2" height="2" class="s"/>
  <rect x="15" y="5" width="2" height="2" class="s"/>
  <!-- Eyes & Cheeks -->
  <rect x="2" y="7" width="3" height="3" class="f"/>
  <rect x="5" y="7" width="4" height="3" class="e"/>
  <rect x="5" y="7" width="2" height="2" class="h"/>
  <rect x="9" y="7" width="6" height="2" class="f"/>
  <rect x="11" y="7" width="2" height="1" class="s"/>
  <rect x="15" y="7" width="4" height="3" class="e"/>
  <rect x="15" y="7" width="2" height="2" class="h"/>
  <rect x="19" y="7" width="3" height="3" class="f"/>
  <!-- Nose & Muzzle -->
  <rect x="2" y="9" width="5" height="3" class="f"/>
  <rect x="17" y="9" width="5" height="3" class="f"/>
  <rect x="11" y="9" width="2" height="1" class="p"/>
  <rect x="7" y="10" width="10" height="2" class="w"/>
  <rect x="8" y="10" width="1" height="1" class="o"/>
  <rect x="15" y="10" width="1" height="1" class="o"/>
  <rect x="11" y="11" width="2" height="1" class="o"/>
  <!-- Whiskers -->
  <rect x="0" y="8" width="2" height="1" class="o"/>
  <rect x="0" y="10" width="2" height="1" class="o"/>
  <rect x="22" y="8" width="2" height="1" class="o"/>
  <rect x="22" y="10" width="2" height="1" class="o"/>
  <!-- Chin & Paws -->
  <rect x="2" y="12" width="2" height="1" class="o"/>
  <rect x="4" y="12" width="16" height="1" class="w"/>
  <rect x="20" y="12" width="2" height="1" class="o"/>
  <rect x="3" y="13" width="2" height="3" class="o"/>
  <rect x="5" y="13" width="4" height="2" class="w"/>
  <rect x="9" y="13" width="6" height="2" class="f"/>
  <rect x="15" y="13" width="4" height="2" class="w"/>
  <rect x="19" y="13" width="2" height="3" class="o"/>
  <rect x="6" y="14" width="1" height="1" class="o"/>
  <rect x="8" y="14" width="1" height="1" class="o"/>
  <rect x="15" y="14" width="1" height="1" class="o"/>
  <rect x="17" y="14" width="1" height="1" class="o"/>
  <rect x="4" y="15" width="16" height="1" class="o"/>
</svg>`,
  },
  {
    path: 'inst/css/base.css',
    name: 'base.css',
    category: 'inst',
    language: 'css',
    description: 'Base CSS template for RStudio GWT workbench UI with token markers.',
    content: `:root {
  --rs-ui-main: {{MAIN_COLOR}};
  --rs-ui-light: {{LIGHT_COLOR}};
  --rs-ui-dark: {{DARK_COLOR}};
  --rs-ui-bg-tint: {{BG_TINT}};
  --rs-ui-border: {{BORDER_COLOR}};
  --rs-ui-hover: {{HOVER_COLOR}};
  --rs-ui-active: {{ACTIVE_COLOR}};
  --rs-ui-cat-data-uri: url("{{CAT_SVG_DATA_URI}}");
}

/* 1. ORANGE PIXEL CAT IN TOP HEADER */
body::before,
#rstudio_shell::before,
#rstudio_container::before,
.rstudio-themes-flat::before {
  content: "" !important;
  position: fixed !important;
  top: 4px !important;
  right: 86px !important;
  width: 36px !important;
  height: 27px !important;
  background-image: var(--rs-ui-cat-data-uri) !important;
  background-size: contain !important;
  background-repeat: no-repeat !important;
  background-position: center !important;
  image-rendering: pixelated !important;
  z-index: 999999 !important;
  pointer-events: auto !important;
  cursor: pointer !important;
  filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.25)) !important;
}

/* 2. TAB HIGHLIGHTS */
.rstudio-themes-flat .gwt-TabLayoutPanelTab-selected {
  border-top: 3px solid var(--rs-ui-main) !important;
  color: var(--rs-ui-main) !important;
}

.rstudio-themes-flat .gwt-TabLayoutPanelTab:hover {
  border-top: 2px solid var(--rs-ui-hover) !important;
}`,
  },
  {
    path: 'tests/testthat/test-color.R',
    name: 'test-color.R',
    category: 'tests',
    language: 'r',
    description: 'Unit tests for color arithmetic and palette derivation.',
    content: `test_that("Color utility functions calculate derivatives correctly", {
  rgb <- hex_to_rgb("#dc6601")
  expect_equal(rgb["r"], c(r = 220))
  expect_equal(rgb["g"], c(g = 102))
  expect_equal(rgb["b"], c(b = 1))

  lighter <- lighten_hex("#dc6601", 0.3)
  darker <- darken_hex("#dc6601", 0.3)
  expect_true(is.character(lighter))
  expect_true(is.character(darker))
})`,
  },
  {
    path: 'tests/testthat/test-css.R',
    name: 'test-css.R',
    category: 'tests',
    language: 'r',
    description: 'Unit tests for CSS generation and SVG token substitution.',
    content: `test_that("CSS generation incorporates tokens and cat SVG data URI", {
  css <- generate_theme_css(main_color = "#dc6601")
  expect_true(grepl("#dc6601", css, fixed = TRUE))
  expect_true(grepl("data:image/svg\\\\+xml;base64,", css))
  expect_true(grepl("body::before", css, fixed = TRUE))
})`,
  },
  {
    path: 'tests/testthat/test-detect.R',
    name: 'test-detect.R',
    category: 'tests',
    language: 'r',
    description: 'Unit tests verifying RStudio installation discovery and path resolution across Electron and Qt layout structures.',
    content: `test_that("rs.ui.detect resolves standard Electron resources/app/www layout", {
  temp_rstudio <- file.path(tempdir(), paste0("mock_rs_electron_", as.integer(runif(1, 10000, 99999))))
  www_dir <- file.path(temp_rstudio, "resources", "app", "www")
  dir.create(www_dir, recursive = TRUE, showWarnings = FALSE)

  index_file <- file.path(www_dir, "index.htm")
  writeLines("<!DOCTYPE html><html><head></head><body></body></html>", index_file)

  pkg_json <- file.path(temp_rstudio, "resources", "app", "package.json")
  writeLines('{"name": "rstudio", "version": "2026.01.0"}', pkg_json)

  detected <- rs.ui.detect(custom_path = temp_rstudio)

  expect_true(detected$detected)
  expect_equal(normalizePath(detected$rstudio_dir, winslash = "/"), normalizePath(temp_rstudio, winslash = "/"))
  expect_equal(normalizePath(detected$index_htm, winslash = "/"), normalizePath(index_file, winslash = "/"))
  expect_equal(normalizePath(detected$www_dir, winslash = "/"), normalizePath(www_dir, winslash = "/"))
  expect_equal(detected$architecture, "electron")
  expect_equal(detected$version, "2026.01.0")

  unlink(temp_rstudio, recursive = TRUE)
})

test_that("rs.ui.detect resolves alternate and legacy layouts in proper priority", {
  temp_nested <- file.path(tempdir(), paste0("mock_rs_nested_", as.integer(runif(1, 10000, 99999))))
  nested_www <- file.path(temp_nested, "resources", "app", "resources", "www")
  dir.create(nested_www, recursive = TRUE, showWarnings = FALSE)
  writeLines("<html></html>", file.path(nested_www, "index.htm"))

  res_nested <- rs.ui.detect(custom_path = temp_nested)
  expect_true(res_nested$detected)
  expect_equal(res_nested$architecture, "electron")
  expect_equal(normalizePath(res_nested$index_htm, winslash = "/"), normalizePath(file.path(nested_www, "index.htm"), winslash = "/"))
  unlink(temp_nested, recursive = TRUE)

  temp_qt <- file.path(tempdir(), paste0("mock_rs_qt_", as.integer(runif(1, 10000, 99999))))
  qt_www <- file.path(temp_qt, "www")
  dir.create(qt_www, recursive = TRUE, showWarnings = FALSE)
  writeLines("<html></html>", file.path(qt_www, "index.htm"))

  res_qt <- rs.ui.detect(custom_path = temp_qt)
  expect_true(res_qt$detected)
  expect_equal(res_qt$architecture, "qt")
  expect_equal(normalizePath(res_qt$index_htm, winslash = "/"), normalizePath(file.path(qt_www, "index.htm"), winslash = "/"))
  unlink(temp_qt, recursive = TRUE)
})`,
  },
  {
    path: 'tests/testthat/test-backup-restore.R',
    name: 'test-backup-restore.R',
    category: 'tests',
    language: 'r',
    description: 'Integration test mocking RStudio directory backup and dry-run.',
    content: `test_that("Backup and restore lifecycle operates cleanly", {
  temp_rstudio <- file.path(tempdir(), "mock_rstudio")
  www_dir <- file.path(temp_rstudio, "resources", "app", "www")
  dir.create(www_dir, recursive = TRUE, showWarnings = FALSE)
  index_file <- file.path(www_dir, "index.htm")
  writeLines("<html><head></head><body></body></html>", index_file)

  mock_detect <- list(
    detected = TRUE,
    rstudio_dir = temp_rstudio,
    index_htm = index_file,
    www_dir = www_dir,
    version = "2026.01.0",
    architecture = "electron",
    is_running = FALSE,
    is_writable = TRUE
  )

  backup_res <- create_ui_backup(mock_detect)
  expect_true(backup_res$success)
  unlink(temp_rstudio, recursive = TRUE)
})`,
  },
];
